import manifest from '../data/media.generated.json';

/** Props for an <img> built from a name generated by scripts/optimize-media.mjs. */
export function imgProps(name, sizes = '100vw') {
  const m = manifest.images[name];
  if (!m) return { src: '', width: 4, height: 3 };
  const widths = m.widths;
  const largest = widths[widths.length - 1];
  return {
    src: `/media/img/${name}-${largest}.webp`,
    srcSet: widths.map((w) => `/media/img/${name}-${w}.webp ${w}w`).join(', '),
    sizes,
    width: m.w,
    height: m.h,
  };
}

/** The largest generated size, for lightboxes. */
export function fullSrc(name) {
  const m = manifest.images[name];
  return m ? `/media/img/${name}-${m.widths[m.widths.length - 1]}.webp` : '';
}

export const videoSrc = (name) => `/media/video/${name}.mp4`;
export const posterSrc = (name) => `/media/video/${name}-poster.jpg`;
